#image: node:latest
#
## Pick zero or more services to be used on all builds.
## Only needed when using a docker container to run your tests in.
## Check out: https://docs.gitlab.com/ee/ci/services/index.html
##services:
##  - mysql:latest
##  - redis:latest
##  - postgres:latest
#
## This folder is cached between builds
## https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/
build:
    script:
       - yarn
       - yarn run build:prod
       - yarn run build:dev
       - dir="${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}"
       - mkdir -p $dir
       - mkdir -p $dir/backup_development
       - mkdir -p $dir/backup_production
       - mkdir -p $dir/liquibase
       - cp -r ./dist_production ./$dir
       - cp -r ./dist_development ./$dir
       - cp -r ./liquibase/ ./$dir
    artifacts:
      paths:
        - ${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}
      expire_in: 1 month
      name: "skim_ID_${CI_COMMIT_REF_NAME}_${CI_PIPELINE_ID}"

